export const CHANGE_NAME = "CHANGE_NAME";
export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD2 = "CHANGE_PASSWORD2";
// export const CHANGE_ERRORS = "CHANGE_ERRORS";
